import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@Styles/globals.css";
import StyledComponentsRegistry from "@Providers/StyledComponentsRegistry";
import { AppContainer } from "@Styles/App.styled";

export const metadata: Metadata = {
  title: "admin test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <AppContainer>{children}</AppContainer>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
